JDA_HOME_DIR: /data/jda
JDA_SETUP_DIR: '{{ JDA_HOME_DIR }}/setup'
AZURE_BLOB_REPO_TYPE: nightly
PLATFORM_VERSION: 2022.1.0.9
ARTIFACTS_LOCATION: /u01/artifacts/cognos
COGNOS_VERSION: null
JAVA_HOME: /etc/alternatives/java_sdk
NODEJS_HOME: /opt/nodejs
LICENSE_MODE: file
LICENSEFILE: 20191_internal_test.lic
LICENSE_API_URL: http://jda-licensing:8080/JDALicensingSE/licapi/license/v1/generate
LICENSE_SERVER_USERNAME: null
LICENSE_SERVER_PASSWORD: '{{ lookup(''azure_keyvault_secret'', ''LICENSE_SERVER_PASSWORD_SECRETNAME'',
  vault_url=KEYVAULT_URI, tenant_id=AZURE_TENANT_ID }}'
LICENSE_JSON_FILE: null
BACKUP_CUSTOMIZATION: false
ENABLE_APPD_CONFIG: false
APPD_JAVA_CONFIG: setapmenv_<customer_name>.sh
EXECUTABLE_FILE: deployplatform
ABPP_UPLOAD_DIR: '{{ JDA_HOME_DIR }}/abppUpload'
WEBSERVER_HOSTNAME: pla3-scpo-dv4.jdadelivers.com
WEBSERVER_PORT: 443
WEBSERVER_SECURE_HTTP: true
APP_GATEWAY_URL: '{{ ''https://'' if WEBSERVER_SECURE_HTTP == True else ''http://''
  }}{{ WEBSERVER_HOSTNAME }}{{ '''' if not WEBSERVER_PORT else '':'' }}{{ WEBSERVER_PORT
  }}'
WHITELIST_URLS: null
SSO_DOMAIN: jdadelivers.com
START_WBEWORKS_SERVER_RETRIES: 15
START_WBEWORKS_SERVER_DELAY_SECONDS: 7
KEYVAULT_NAME: kv-by-core-automation-01
KEYVAULT_URI: https://{{ KEYVAULT_NAME }}.vault.azure.net
AZURE_CLIENT_ID: null
AZURE_SECRET: null
AZURE_TENANT_ID: c9536685-1262-420b-a94b-4f5420284680
ORACLE_HOME: /opt/oracle/instantclient
DB_HOST: dvpla31503031.jdadelivers.com
DB_PORT: 1521
DB_SID: DVHDE0EF
SYSTEM_USER: system
PLATFORM_CREATE_DATABASE_ASYNC_TIMEOUT_SECONDS: 3600
PLATFORM_DB_PATCH_ROLLBACK_SETUP: true
SYSTEM_PASSWORD: '{{ lookup(''azure_keyvault_secret'', ''dv4-oracleSystemPassword-DVHDE0EF'',
  vault_url=DBA_KEYVAULT_URI) }}'
JDA_SYS_PASSWORD: '{{ lookup(''azure_keyvault_secret'', ''dv4-scpo-db-jdasystem-pwd'',
  vault_url=DB_KEYVAULT_URI) }}'
WWF_PASSWORD: '{{ lookup(''azure_keyvault_secret'', ''dv4-scpo-db-wwf-pwd'', vault_url=DB_KEYVAULT_URI)
  }}'
EMA_PASSWORD: '{{ lookup(''azure_keyvault_secret'', ''dv4-scpo-db-wwf-pwd'', vault_url=DB_KEYVAULT_URI)
  }}'
ABPP_PASSWORD: '{{ lookup(''azure_keyvault_secret'', ''dv4-scpo-db-abpp-pwd'', vault_url=DB_KEYVAULT_URI)
  }}'
ACTIVEMQ_HOST: dvpla31502031.jdadelivers.com
ACTIVEMQ_PORT: 61616
BROKER_NAME: JDAMessageBroker
IS_ACTIVEMQ_EXTERNAL: true
ACTIVEMQ_USER: admin
ACTIVEMQ_ENCRYPTED_PASSWORD: '{E:AES}01a0a1919f1116e8a4ee2961a095cf74'
KEY_STORE_FILE: '{{ JDA_SETUP_DIR }}/ssl.jks'
KEY_STORE_PASSWORD: '{{ lookup(''azure_keyvault_secret'', ''dv4-scpo-app-keystore-pwd'',
  vault_url=AP_KEYVAULT_URI) }}'
KEY_STORE_ENCRYPTED_PASSWORD: '{E:AES}251ce51f32cba57df39b4fc2cac73a609ca1b4e61be860de9325e830ce409661'
KEY_ENCRYPTED_PASSWORD: '{E:AES}251ce51f32cba57df39b4fc2cac73a609ca1b4e61be860de9325e830ce409661'
ENABLE_SSL: true
INSTALL_CA_CERT: true
CA_SECRET_NAME: scpo-jdadelivers-com
CA_SUBSCRIPTION_ID: sub-by-cld-repo-prod-01
CA_VAULT_NAME: kv-by-repo-certs-eus2
RESOURCE_GROUP: rg-pla3-15-dv4-eus2
PLATFORM_ENABLE_JMX_AUTHENTICATION: false
COMMON_TSHIRT_SIZE: Demo
PLATFORMUTILS_FOUNDATION_TABLESPACE: WWFDATA
PLATFORMUTILS_FLEXIBLE_EDITOR_TABLESPACE: WWFDATA
PLATFORMUTILS_EMA_TABLESPACE: WWFDATA
PLATFORM_REPORTING_GATEWAY_HOST: null
PLATFORM_REPORTING_DISPATCHER_HOST: null
HELP_LANG: en
PLATFORMHELP_HOST: null
COMMON_HELP_URL: https://scpohelp-test-2019-1-2.jdadelivers.com/jda
PLATFORM_HELP_TYPE: common
PLATFORM_SETUP_DIR: '{{ JDA_SETUP_DIR }}/platform'
PLATFORM_INSTALL_DIR: '{{ JDA_HOME_DIR }}/app'
PLATFORM_ENABLE_MODERN_CANVAS: true
CONTEXT_ROOT: '{{ ''scpo/ui/v1'' if ENABLE_PORTAL == True else ''jda'' }}'
DATACONTEXT_API_VERSION: '{{ ''v2'' if ENABLE_PORTAL == True else ''v1'' }}'
PLATFORM_CUSTOM_LOGO: false
PLATFORM_SHELL_BANNER_LOGO: customer-name_custom_banner_logo.jpg
PLATFORM_LOGIN_PAGE_LOGO: customer-name_custom_login_logo.jpg
PLATFORM_INSTALL_REPORTING: false
PLATFORM_ENABLE_MONITOR: false
PLATFORM_ENVIRONMENT_NAME: Dev
PLATFORM_HOST_ENTERPRISE: BlueYonder
PLATFORM_SERVER_PORT: 7001
PLATFORM_SERVER_SSL_PORT: 7002
PLATFORM_AJP_PORT: 7003
PLATFORM_JMX_PORT: 7004
PLATFORM_SHUTDOWN_PORT: 7005
PLATFORM_JDA_SYS_USER: JDA_SYSTEM
PLATFORM_WWF_USER: WWFMGR
PLATFORM_WWF_ENCRYPTED_PASSWORD: '{E:AES}77452fe21da477d31a512e2d315d0d3c9ca1b4e61be860de9325e830ce409661'
PLATFORM_WWF_CONNECTION_POOL_INITIAL: 5
PLATFORM_WWF_CONNECTION_POOL_MAX: 30
PLATFORM_WWF_CONNECTION_POOL_INCREMENT: 5
PLATFORM_EMA_USER: WWFMGR
PLATFORM_EMA_ENCRYPTED_PASSWORD: '{E:AES}77452fe21da477d31a512e2d315d0d3c9ca1b4e61be860de9325e830ce409661'
PLATFORM_EMA_CONNECTION_POOL_INITIAL: 5
PLATFORM_EMA_CONNECTION_POOL_MAX: 30
PLATFORM_EMA_CONNECTION_POOL_INCREMENT: 5
PLATFORM_ABPP_USER: ABPPMGR
PLATFORM_ABPP_ENCRYPTED_PASSWORD: '{E:AES}11982fe555f17c0db2777177f46974169ca1b4e61be860de9325e830ce409661'
PLATFORM_JVM_SERVER_MEM_ARGS: -Xms2G -Xmx2G
PLATFORM_JVM_SRE_MEM_ARGS: -Xms256M -Xmx512M
PLATFORM_JVM_BATCH_MEM_ARGS: -Xms32M -Xmx64M
PLATFORM_EMAIL_SYSADMIN_ADDRESS: admin@jda.com
PLATFORM_EMAIL_SYSTEM_ADDRESS: user@jda.com
PLATFORM_EMAIL_SMTP_HOST: hyder.jda.com
PLATFORM_GATEWAY_ALIAS: ibmcognos
PLATFORM_REPORTING_GATEWAY_PORT: 80
PLATFORM_REPORTING_DISPATCHER_PORT: 9300
PLATFORMDATACONTEXT_PORT: 6001
PLATFORMDATACONTEXT_SSL_PORT: 6002
PLATFORMDATACONTEXT_SETUP_DIR: '{{ JDA_SETUP_DIR }}/platformdatacontext'
PLATFORMDATACONTEXT_INSTALL_DIR: '{{ JDA_HOME_DIR }}/datacontext'
PLATFORMDATACONTEXT_WWF_ENCRYPTED_PASSWORD: 816628bae7029be794b0e069ac7576e2:08251240ddfb20ceeda4f92d99b9c1c1
PLATFORMHELP_SERVER_PORT: 8080
PLATFORMHELP_SERVER_SSL_PORT: 8001
PLATFORMHELP_AJP_PORT: 8002
PLATFORMHELP_SHUTDOWN_PORT: 8004
ENABLE_OAUTH: false
B2C_CLIENT_ID: null
B2C_REDIRECT_URL: null
B2C_EXCLUDE_URL: null
B2C_SUBJECT: null
B2C_POLICY_SIGNIN: b2c_1a_signin
B2C_BY_DOMAIN_HINT: null
B2C_BY_SCOPES: null
B2C_HOST: null
B2C_TENANT: null
B2C_KEYVAULT_NAME: null
B2C_KEYVAULT_SECRET_NAME: null
B2C_BY_API_ID: null
NAMESPACE_ID: OPENID
END_POINT_URL: https://{{ B2C_HOST }}:443/{{ B2C_TENANT }}/{{ B2C_POLICY_SIGNIN }}/v2.0/.well-known/openid-configuration
CERTIFICATE_NAME: null
COLLABORATION_SERVICE_URL: https://apideveloper.jdadelivers.com/api-details#api=lui-services_collaboration_v1
NOTIFICATION_SERVICE_URL: https://apideveloper.jdadelivers.com/api-details#api=lui-services_notification_v1
VOTING_SERVICE_URL: https://apideveloper.jdadelivers.com/api-details#api=lui-services_voting_v1
ENABLE_PORTAL: false
CONTENT_SECURITY_POLICY_HEADER: frame-ancestors ''self'' {{PORTAL_URL}} {{APP_GATEWAY_URL}}
PORTAL_LIAM_TENANT_HOST: null
PORTAL_LIAM_POLICY_NAME: b2c_1a_signin
PORTAL_LIAM_BY_SCOPES: by.scpo
PORTAL_LIAM_DOMAIN_HOST: null
PORTAL_LIAM_API_ID: null
PORTAL_LIAM_DOMAIN_HINT: null
PORTAL_API_GATEWAY_ENABLED: false
PORTAL_INDEX_PAGE_URL: '{{ APP_GATEWAY_URL }}/{{ CONTEXT_ROOT }}/index.html'
PORTAL_URL: null
PORTAL_MFE_REGISTRATION: null
PORTAL_SCPO_MFE_REG_API_KEY: null
PORTAL_SCPO_MFE_REG_API_ID: null
PORTAL_SCPO_MFE_DISPLAY_NAME: null
PORTAL_SCPO_MFE_HEADER_NAME: null
PORTAL_SCPO_FRAME_URL: '{{APP_GATEWAY_URL}}/{{CONTEXT_ROOT}}/mfe/mfe.html'
PORTAL_SCPO_ENABLED: true
PORTAL_SCPO_NAME_SPACE: scpo
PORTAL_SCPO_REALM: null
M2M_CLIENT_ID: null
M2M_CLIENT_SECRET: null
M2M_SUBJECT_ID: null
M2M_USER: null
PORTAL_LOGOUT_WEBHOOK_SUBSCRIBE_URL: null
PORTAL_LOGOUT_URL: /shell/rest/authentication/logout/1.0
APP_POST_LOGOUT_URL: '{{ APP_GATEWAY_URL }}/{{ CONTEXT_ROOT }}/shell/home'
ansible_python_interpreter: /usr/bin/python3
COGNOS_SETUP_FILES: '{{ JDA_HOME_DIR }}/cognos_setup_files'
COGNOS_INSTALLER_UI: SILENT
COGNOS_USER_LANGUAGE_RESULTS: English
COGNOS_USE_DEFAULTS: 0
COGNOSSERVER_SETUP_DIR: '{{ JDA_HOME_DIR }}/cognosserversetup'
COGNOSSERVER_INSTALL_DIR: '{{ JDA_HOME_DIR }}/serverinstalldir'
COGNOSSERVER_DISPATCHER_HOST: null
COGNOSSERVER_DISPATCHER_PORT: null
COGNOSERVER_LOG_PORT: null
COGNOSERVER_SHUTDOWN_PORT: null
COGNOSERVER_CONFIG_PORT: null
COGNOSERVER_CONFIG_SYNC_PORT: null
COGNOS_DB_USER: null
COGNOS_DB_PASSWORD: '{{ lookup(''azure_keyvault_secret'', ''dv4-scpo-db-cognos-pwd'',
  vault_url=DB_KEYVAULT_URI) }}'
COGNOSSERVER_MAIL_SERVER_HOST: null
COGNOSSERVER_MAIL_SERVER_PORT: null
COGNOSSERVER_MAIL_SERVER_USER: ReportingAdmin
COGNOSSERVER_MAIL_SERVER_PASSWORD: null
COGNOSSERVER_SENDER_EMAIL_ADDRESS: null
COGNOSSERVER_SCHEMA: null
COGNOSSERVER_DBCONTENT_TYPE: Oracle
REPORTING_ORACLE_HOME: null
COGNOSSERVER_SYSTEM_USER_TABLESPACE: CRNDATA
COGNOSSERVER_USER_TABLESPACE_DATAFILE_PATH: /u02/app/oracle/oradata
COGNOSSERVER_USER_TABLESPACE_DATAFILE_PATH_NAME: '{{ COGNOSSERVER_USER_TABLESPACE_DATAFILE_PATH
  }}/{{ DB_SID }}/{{COGNOSSERVER_SYSTEM_USER_TABLESPACE}}01.dbf'
COGNOSREPORTING_POSTINSTALL_ASYNC_TIMEOUT_SECONDS: 3600
COGNOSGATEWAY_SETUP_DIR: '{{ JDA_HOME_DIR }}/cognosgatewaysetup'
COGNOSGATEWAY_INSTALL_DIR: '{{ JDA_HOME_DIR }}/gatewayinstalldir'
COGNOSGATEWAY_HOST: '{{ COGNOSSERVER_DISPATCHER_HOST }}'
COGNOSGATEWAY_PORT: null
COGNOSCLIENT_SETUP_DIR: null
COGNOSCLIENT_INSTALL_DIR: '{{ COGNOSCLIENT_SETUP_DIR }}\\CognosClient_FM'
COGNOSCLIENT_BINARY_NAME: cognosclient-disk1-{{ COGNOS_VERSION }}-windows.zip
COGNOSCLIENT_PRODUCT_NAME: Framework Manager Admin Client
COGNOSCLIENT_DISPATCHER_HOST: null
COGNOSCLIENT_DISPATCHER_PORT: null
APPLICATION_REPORTS_INSTALL_DIR: '{{ JDA_HOME_DIR }}/utils'
JDAPLATFORM_LOGIN_USERNAME: System
JDAPLATFORM_LOGIN_USERPASSWORD: '{E:AES}b61cd9349d66b84b32d15cdf1910d530'
MANAGEMODEL_APPLICATION_NAME: All
IMPORTREPORTS_APPLICATION_ZIP: All
IS_COMMON_COGNOS: false
COGNOS_APPLICATION_NAME: SCPO
IS_SRE_ON_STRATOSPHERE: false
GEOGRAPHY: us
STS_ENV: staging
SYSD_ROOT: '{{ JDA_HOME_DIR }}/systemd'
ACTIVEMQ_WEBCONSOLE_PORT: 8161
READ_ONLY_USER: SCP_PLAN_READ_ONLY
READ_ONLY_USER_PASSWORD: '{{ lookup(''azure_keyvault_secret'', ''dv4-scpo-db-rouser-pwd'',
  vault_url=DBRO_KEYVAULT_URI) }}'
INF_KEYVAULT_URI: https://kv-pla3-scpo-inf-np-eus2.vault.azure.net
AP_KEYVAULT_URI: https://kv-pla3-scpo-ap-np-eus2.vault.azure.net
DB_KEYVAULT_URI: https://kv-pla3-scpo-db-np-eus2.vault.azure.net
DBA_KEYVAULT_URI: https://kv-pla3-scpo-dba-np-eus2.vault.azure.net
DBRO_KEYVAULT_URI: https://kv-pla3-scpo-dbr-np-eus2.vault.azure.net
