name: Simple Action workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a

      - name: repo Checkout
        uses: actions/checkout@v1

      - name: List Files after checkout
        run: |
          pwd
          ls -a

      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with: 
          who-to-greet: "Kishore"
      - name: Get Time of Greeting
        run: echo "${{ steps.greet.outputs.time }}"