name: Checkout
on: [push]

jobs:
  checkout-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: list files before
        run: ls -a
      - name: checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.MYTOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List files after
        run: ls -a
