name: First Workflow

on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps: 
      - name: Single line command
        run: echo "Hello World"
      - name: Multi line command
        run: |
          node -v
          npm -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo commads
        run: Write-Output "Windows String"
