name: Check yq 

on: 
  push:

jobs:
  Checking-Yq:
    runs-on: ubuntu-latest
    steps:
        - name: Repo checkout
          uses: actions/checkout@v3
        - name: Get DB Host val from config file
          id: get_val
          uses: mikefarah/yq@master
          with:
            cmd: | 
                host=echo $(yq '.DB_HOST' '.github/yaml/platform.yaml')
                port=echo $(yq '.DB_PORT' '.github/yaml/platform.yaml')
                echo "host=$host" >> $GITHUB_ENV
                echo "port=$port" >> $GITHUB_ENV
        - name: Get DB Value from yaml file
          run: |
            echo $host
            echo $port