name: Check yq 

on: 
  push:

jobs:
  Checking-Yq:
    runs-on: ubuntu-latest
    steps:
        - name: Get Path
          run: |
            echo pwd
        - name: Get DB Host val from config file
          id: get_val
          uses: mikefarah/yq@master
          with:
            cmd: yq '.DB_HOST' '.github/yaml/platform.yaml'
        - name: Get DB Value from yaml file
          run: |
            echo ${{steps.get_val.outputs.result}}