name: Check yq 

on: 
  push:

jobs:
  Checking-Yq:
    runs-on: ubuntu-latest
    steps:
        - name: Get DB Host val from config file
          uses: mikefarah/yq@master
          with:
            cmd: pwd
                 dbHost=yq '.DB_HOST' '.github/yaml/platform.yaml'
                 echo $dbHost