name: Hello World Workflow

on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu_latest
        steps:
            - uses: actions/checkout@v2
            - name: Hello World
              run: echo "Hello World"
              shell: bash
    goodbye:
        runs-on: ubuntu_latest
        steps:
            - name: goodbye World
              run: echo "goodbye world"
              shell: bash



    