name: Pull Request Comments
on:
  pull_request_target:
    types: [opened]
jobs:
  pr-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR request
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.owner,
                issue_number: context.issue.number,
                body: 'Thanks for contributing..',
            })  